//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashMich.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HashMich.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap browse {
            get {
                object obj = ResourceManager.GetObject("browse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calculator {
            get {
                object obj = ResourceManager.GetObject("calculator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
        /// </summary>
        internal static System.Drawing.Icon HashMich {
            get {
                object obj = ResourceManager.GetObject("HashMich", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate hashes ähnelt.
        /// </summary>
        internal static string MainForm_cbContext_CheckedChanged_CalculateHashValue {
            get {
                return ResourceManager.GetString("MainForm_cbContext_CheckedChanged_CalculateHashValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error: {0} ähnelt.
        /// </summary>
        internal static string MainForm_cbContext_CheckedChanged_Error0 {
            get {
                return ResourceManager.GetString("MainForm_cbContext_CheckedChanged_Error0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculating... ähnelt.
        /// </summary>
        internal static string MainForm_Compute_Calculating {
            get {
                return ResourceManager.GetString("MainForm_Compute_Calculating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculation... ähnelt.
        /// </summary>
        internal static string MainForm_Compute_Calculation {
            get {
                return ResourceManager.GetString("MainForm_Compute_Calculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown algorithm. ähnelt.
        /// </summary>
        internal static string MainForm_Compute_UnknownAlgorithm {
            get {
                return ResourceManager.GetString("MainForm_Compute_UnknownAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Browse filesystem ähnelt.
        /// </summary>
        internal static string MainForm_InitializeComponent_BrowseFilesystem {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_BrowseFilesystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate hashes ähnelt.
        /// </summary>
        internal static string MainForm_InitializeComponent_CalculateHashes {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_CalculateHashes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Context menu entry ähnelt.
        /// </summary>
        internal static string MainForm_InitializeComponent_ContextMenu {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_ContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Double click saves value to clipboard ähnelt.
        /// </summary>
        internal static string MainForm_InitializeComponent_DoubleClickSavesValueToClipboard {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_DoubleClickSavesValueToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die File Hash Calculator ähnelt.
        /// </summary>
        internal static string MainForm_InitializeComponent_FileHashCalculator {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_FileHashCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Help ähnelt.
        /// </summary>
        internal static string MainForm_InitializeComponent_Help {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste an hash here to compare with the above results: ähnelt.
        /// </summary>
        internal static string MainForm_InitializeComponent_PasteAnHashHereToCompareWithTheAboveResults {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_PasteAnHashHereToCompareWithTheAboveResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Path: ähnelt.
        /// </summary>
        internal static string MainForm_InitializeComponent_Path {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Register to user&apos;s context menu ähnelt.
        /// </summary>
        internal static string MainForm_InitializeComponent_RegisterToUserSContextMenu {
            get {
                return ResourceManager.GetString("MainForm_InitializeComponent_RegisterToUserSContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die - calculates hashes for the given file{0}- accepts the file as parameter{0}- can be registered in the user&apos;s context menu{0}- color highlights the matching value in a control{0}- copies the matching value to the clipboard on double click ähnelt.
        /// </summary>
        internal static string MainForm_label3_Click_HashMich00CalculatesHashesForTheGiveFile0AcceptsTheFileAsParameter0CanBeRegisteredInTheUserSContextMenu0DoubleClickCopiesTheValueToTheClipbopard {
            get {
                return ResourceManager.GetString("MainForm_label3_Click_HashMich00CalculatesHashesForTheGiveFile0AcceptsTheFileAsPa" +
                        "rameter0CanBeRegisteredInTheUserSContextMenu0DoubleClickCopiesTheValueToTheClipb" +
                        "opard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string MainForm_MainForm_Error {
            get {
                return ResourceManager.GetString("MainForm_MainForm_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid file path: {0} ähnelt.
        /// </summary>
        internal static string MainForm_MainForm_InvalidFilePath0 {
            get {
                return ResourceManager.GetString("MainForm_MainForm_InvalidFilePath0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} hash copied to clipboard! ähnelt.
        /// </summary>
        internal static string MainForm_TxtHash_DoubleClick_0HashCopiedToClipboard {
            get {
                return ResourceManager.GetString("MainForm_TxtHash_DoubleClick_0HashCopiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copied ähnelt.
        /// </summary>
        internal static string MainForm_TxtHash_DoubleClick_Copied {
            get {
                return ResourceManager.GetString("MainForm_TxtHash_DoubleClick_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hash value is empty! ähnelt.
        /// </summary>
        internal static string MainForm_TxtHash_DoubleClick_HashValueIsEmpty {
            get {
                return ResourceManager.GetString("MainForm_TxtHash_DoubleClick_HashValueIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown Algorithm ähnelt.
        /// </summary>
        internal static string UnknownAlgorithm {
            get {
                return ResourceManager.GetString("UnknownAlgorithm", resourceCulture);
            }
        }
    }
}
